
name: Github-Actions-SSH
on:
  watch:
    types: started
  workflow_dispatch:
jobs:
  Github-Actions-SSH:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: checkout
        uses: actions/checkout@main
      - name: 环境搭建
        run: |
          sudo snap install ffmpeg --channel=latest/edge
          pip3 install youtube-dl
          chmod 777 ./OneDriveUploader
      - name: 运行SSH
        uses: mxschmitt/action-tmate@master
